### PR TITLE
change default fee from 1 to 0.5 sat/byte

### PR DESCRIPTION
**Pull request by yoursmengle**

### CODE REVIEW

**Comment by yoursmengle** [comment]
Change default fee from 1 to 0.5 sat/bytes

**Comment by teran-mckinney** [comment]
Default fee should be a constant with some kind of explanation.

I think this is a little ridiculous, IMO. Do we even support floats here?

**Comment by AustEcon** [comment]
Yes it should be something more like `DEFAULT_FEE_SLOW` from `network.fees` and I wasn't aware that the vast majority of miners on mainnet are now accepting 0.5 sat/byte tx fee - is that the case? 

I'd rather stay conservative for default settings if not and keep it as 1 sat/byte otherwise people will encounter no end of trouble with block explorers etc. not confirming their transaction and coins 'stuck in limbo' etc...

**Comment by AustEcon** [comment]
I think we should support this feature though eventually but would require a bit of extra work to handle floats and round up the fee estimation to the nearest integer. 
Would also need tests.

**Pull request closed without merging**
