### PR TITLE
Replace dead BitcoinSVRates with CryptoCompareRates

### PR DESCRIPTION
**Pull request by teran-mckinney**
This looks to be a good API and even allows Tor.

### CODE REVIEW

**Comment by AustEcon** [comment]
Thanks for the PR! 

Will that endpoint work with no additional setup or does user need to go get a pubkey from website?
If they do need a pubkey maybe we need an error message to instruct user of what to do. 
And could maybe have a function that sets an environment variable to the pubkey for hasstle-free continued use.

Looks good though. If it works straight away without pubkey addition could merge as-is.

**Comment by AustEcon** [comment]
Okay - looks like (in FAQs) that they will support a free, public API for a limited time but will probably get worse over time. I can merge this now but might be another task for later to add a little function for tacking on an api key as an environment variable that gets added to the request header.

**Comment by teran-mckinney** [comment]
No problem! Thanks for looking into this.

It's working great for me so far. Been runnnig it on 10 servers, polling hourly, for a couple months now. Can definitely add API key support in the future if needed. bitcoinsvrates.com is dead anyways so should be a step in the right direction.

**Comment by AustEcon** [comment]
Awesome thanks :)

**Pull request merged**
