### PR TITLE
Change default fee from 1 to 0.5 sat per byte

### PR DESCRIPTION
**Pull request by gitzhou**

### CODE REVIEW

**Comment by AustEcon** [comment]
Hey. Thanks for this!

I assume there are no side effects to be aware of in terms of propagating a 0.5sat/byte fee across the network and having it show on Whatsonchain etc. ?
I want the default to be at the lowest, **safe level** (emphasis on the word **safe**). But if that is now at 0.5 sat/byte then great :slightly_smiling_face: 

But OTOH, if it is only e.g. 70% of the network and it causes some strange behavior then what we need is to keep the default fee at the safe level but make it so that when a lower fee is preferred that bitsv will accommodate and round up to nearest satoshi. (i.e. perhaps the user has access to node(s) that **do accept** the lower tx fee rate...).

I'll need a moment to check this over - is bitindex rejecting it because of the lower fee or is it just down?

**Comment by gitzhou** [comment]
Thanks, Aust. Sorry for my less consideration. 

Unconfirmed tx of fee 0.5 can be broadcasted with BitIndex API inside(others not tested yet).
WoC and Blockchair are both ok with it.





Depends on your comments, I prefer not to change the default transaction fee if it's safer to keep 1 sat/B, yet it would be great to give support to a custom fee of 0.5

What would you say about this?  😆

**Comment by teran-mckinney** [comment]
As a rule of thumb, the default speed should be medium, not fast or slow. It's best to start in the middle range for such a thing, so someone can go up or down if wanted.

In which case, I think the most fair compromise would be medium is 1 sat/byte, fast is 2 sat/byte, and slow is 0.5 sat/byte. So the default would stay the same numerically, but be moved to the middle of the range.

What do you think?

**Comment by gitzhou** [comment]
> As a rule of thumb, the default speed should be medium, not fast or slow. It's best to start in the middle range for such a thing, so someone can go up or down if wanted.
> 
> In which case, I think the most fair compromise would be medium is 1 sat/byte, fast is 2 sat/byte, and slow is 0.5 sat/byte. So the default would stay the same numerically, but be moved to the middle of the range.
> 
> What do you think?

Yes, I agree

**Comment by gitzhou** [comment]
I push a new commit per our discussion.

- Revert some previous change
- Change the parameter type of fee from `int` to `float`, in order to support custom fee under 1 sat/B

**Comment by teran-mckinney** [comment]
Looks pretty good to me, thank you! However, I would import DEFAULT_FEE_MEDIUM and use it with op_return instead of hardcoding the 1 there. It's pedantic but I think clearer. And future updates to the constants would reflect wherever they are used.

What do you think, @AustEcon?

**Comment by gitzhou** [comment]
> I would import DEFAULT_FEE_MEDIUM and use it with op_return instead of hardcoding the 1 there.

Does this mean to change the following method

```
def create_op_return_tx(self, list_of_pushdata, outputs=None, fee=1, unspents=None, leftover=None, combine=False):
```

to

```
def create_op_return_tx(self, list_of_pushdata, outputs=None, fee=DEFAULT_FEE_MEDIUM, unspents=None, leftover=None, combine=False):
```

BTW, should we change the comments?

```
:param fee: The number of satoshi per byte to pay to miners. By default
            BitSV will use a fee of 1 sat/byte
:type fee: ``float``
```

change it to the following

```
:param fee: The number of satoshi per byte to pay to miners. By default
            BitSV will use a fee of DEFAULT_FEE_MEDIUM
:type fee: ``float``
```

**Comment by AustEcon** [comment]
> Looks pretty good to me, thank you! However, I would import DEFAULT_FEE_MEDIUM and use it with op_return instead of hardcoding the 1 there. It's pedantic but I think clearer. And future updates to the constants would reflect wherever they are used.
> 
> What do you think, @AustEcon?

Yes - I agree. Not a huge deal in this case but it is good practice to do this. Avoids inconsistencies. Centralizes control to where the constant is defined.

Up to you re: the comments @gitzhou

**Comment by AustEcon** [comment]
I've taken it for a spin now. Works fine. I'm happy. 
Thanks @gitzhou. Either myself or Teran can merge after that last little change is in. 😃

**Comment by gitzhou** [comment]
Haha, great thanks to @teran-mckinney and @AustEcon 😄

**Comment by gitzhou** [comment]
To avoid misunderstanding, change the PR title

**Comment by AustEcon** [comment]
Yeah I edited the commit messages a bit - hope you don't mind

**Comment by teran-mckinney** [comment]
Thank you!

**Comment by gitzhou** [comment]
Thank YOU! @teran-mckinney  😄

**Pull request merged**
