### PR TITLE
simple network service for local full-node

### PR DESCRIPTION
**Pull request by xloem**
Hi,

I made a basic backend for connecting the API to a locally running node via jsonrpc, rather than a web service.

I've used this locally to successfully upload a file with polyglot, but I haven't added it to NetworkAPI here as I wasn't sure of the interface for this.  It passes the testsuite (if 3 nodes are all running locally for the 3 different network types), but I haven't manually tested anything or inspected whether the testsuite covers everything I wrote.

### CODE REVIEW

**Comment by AustEcon** [comment]
Awesome! Thanks so much. I will need a bit of time to take a closer look. And probably Teran too. But my first impression (from my phone) is that I like it. There have been requests for this kind of thing + Reg test.

Thanks!

**Comment by teran-mckinney** [comment]
Hey! This is very cool but I feel bad that you reinvented the wheel over this. Have you seen the pull request in bit where this is implemented? I imagine it would copy over almost identically.

https://github.com/ofek/bit/pull/76

**Comment by teran-mckinney** [comment]
By the way, we're generally dropping cashaddr, I need to pull more of those bits out. No need to support it in something new.

**Comment by xloem** [comment]
Thanks, I didn't really know that `bitsv` was forked from `bit`.
It looks like the bit fork is more polished.  This code handles some transaction cases it doesn't, but lacks the docs etc.

**Comment by AustEcon** [comment]
To be honest. Just reading over the code... I find the implementation here much more readable than the bit one. 
Also with our refactoring we no longer have to append _testnet or _stn versions for all 5 bread and butter functions.
I'm open to going our own way on this one but we can still learn from the bit repo and take the best parts with us. For example, the "connect_to_node" classmethod idea in NetworkAPI section is a good idea to override the default and switch over to using the bitcoin node.

**Comment by teran-mckinney** [comment]
Bitcoin SV node returns cashaddr? That's terrible, needs to get fixed. Good to know.

I was just curious for your thoughts on that implementation and to see if it it solved any issues for you. I can review both and give you feedback, just wanted you to see it first.

**Comment by AustEcon** [comment]
Cashaddr is going to be removed soon. https://twitter.com/BSVGlobal/status/1149737932149989378?s=20

**Comment by xloem** [comment]
That’s great they resolved the cashaddr thing.  I’m away from the Internet for the weekend and can’t work on this more myself until some future day.

**Comment by AustEcon** [comment]
I've really been wanting to cut a new release (ideally tomorrow). So what I might do, is leave this fullnode implementation out of this next release but I can follow it up in quick succession with a new minor version update.

**Comment by teran-mckinney** [comment]
Yeah, I would love to have full node support but I think a minor release before that would be good.

**Comment by teran-mckinney** [comment]
Hey! We've cut our releases. I'd love to see local node support added to bitsv.

Also, node support was merged into bit. Might be worth taking one more look at even just for ideas.

https://github.com/ofek/bit/pull/76

**Comment by AustEcon** [comment]
Sorry I took so long with this... I made some modifications because of all of the recent changes that have broken this PR.. and then just decided to merge. I will close this now.

Thanks so much for this. Great addition :smiley:

**Pull request closed without merging**
